### ISSUE TITLE
Can't specify confidence threshold for inference export

### ISSUE THREAD

**Issue by rbavery** [developmentseed/ml-enabler#100]
![Screenshot from 2021-08-16 14-54-51](https://user-images.githubusercontent.com/22258697/129634317-22c786c3-8b87-411b-8003-075f7ef093b3.png)

The slider under "Singl Inference Options" for the threshold isn't movable and stays at 50% . Also, the exported inference results still contain confidence scores that are less than .5

**Comment by ingalls** [comment]
This is intentional at the moment as those options are "Single Inference" options. When `Inferences=All` it doesn't know which inference it should be filtering on and therefore is greyed out.

If you have suggestions to make this more intuitive feel free to reopen a new ticket
