### ISSUE TITLE
Requirements Conflict text-unidecode

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/ml-enabler#15]
`ERROR: Could not find a version that matches text-unidecode==1.2,==1.3`

Looks like factory-boy requires Faker which requries text-unidecode==1.2 but that conflcts with 1.3 specified in the requirements
```
factory-boy==2.12.0
  - Faker [required: >=0.7.0, installed: 1.0.7]
    - python-dateutil [required: >=2.4, installed: 2.8.1]
      - six [required: >=1.5, installed: 1.14.0]
    - six [required: >=1.10, installed: 1.14.0]
    - text-unidecode [required: ==1.2, installed: 1.2]
```

**Comment by ingalls** [comment]
The migration to Node has been completed and as such this issue can be closed.
