### ISSUE TITLE
Improve User Experience with running the same model inference over multiple aois 

### ISSUE THREAD

**Issue by martham93** [developmentseed/ml-enabler#29]
currently, UI of the map of inferences works best if we created different version of the model if we want to inference over vastly different AOIs even if it it's the same model but re-uploading the same model.zip file isn't ideal. 

I'm not sure which is a better approach

* allowing for a better UI inference display experience with multiple AOIs (each AOI has it's own bbox that's displayed and named on the map) 
or 
* still keeping separate prediction versions for each AOI, but having the version of the model accessible so the user can just select it or something so it doesn't need to be re-uploaded by the user, or we have like model version `1.0.0` then there are separate inference stacks that a user can create per AOI underneath that v `1.0.0` model 

this is beyond the scope of this issue, but still related, would be thinking about how to handle AOI specific exports, especially if we go with the first approach. 

cc @ingalls

**Comment by ingalls** [comment]
Closed by: https://github.com/developmentseed/ml-enabler/pull/30
