### ISSUE TITLE
Model Metadata JSON

### ISSUE THREAD

**Issue by martham93** [developmentseed/ml-enabler#36]
We've been discussing model meta-data a lot recently, so I wanted to get an issue up on the idea, and discuss format, and how it will be used in ml-enabler. 

One idea would be to have the user upload a json file with appropriate model meta-data, some aspects of the model meta-data json file could be used to automatically populate the `advanced options` for the re-training task for increased flexibility.

The model-meta data json file would be uploaded during the initial project creation step. 

model meta-data json could have: input shape, output shape, number of classes, class names 

some examples of what would be passed from the model meta-data json to re-training would be 

```{`base model`: "resnet50"
  `tf_batch_size`: 8,
        ` tf_train_steps`:200,
        ` tf_dense_size`:256,
         `tf_dense_dropout_rate`:0.34,
         `tf_dense_size`:153,
         `tf_dense_dropout_rate`: .35,
         `tf_dense_activation`:"relu'"
         `tf_learning_rate`:0.00001,
        ` tf_optimizer`: "adam"}```

**Comment by ingalls** [comment]
@martham93 deployed this with #41
