### ISSUE TITLE
ML-Enabler Staging Memory + Model.zip Upload

### ISSUE THREAD

**Issue by martham93** [developmentseed/ml-enabler#65]
Staging is inconsistent if `model.zip` uploads fail or work. Sometimes they fail at 100%,  and other times they fail earlier in the upload process. The size of the model.zip file isn't the issue because these models are consistent with other model sizes, and a model that fails to upload to staging will upload successfully to prod. Sometimes a model will fail to upload, then a little bit later on after creating a new project version or re-trying the same project version upload will succeed.  I haven't really figured out a pattern.
The AWS logs indicate that that sometimes memory can't be allocated, so I think we should explore increasing memory allocations. 

cc @ingalls

**Comment by ingalls** [comment]
I've doubled the memory on both prod & staging and we haven't seen any issues since then. Feel free to reopen if this once again becomes an issue.
